import random

def escape_sql(val):
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    return str(val)

categories = [
    ("Fruits & Vegetables", "fruits-vegetables.png"),
    ("Dairy & Bakery", "dairy-bakery.png"),
    ("Staples", "staples.png"),
    ("Snacks & Branded Foods", "snacks.png"),
    ("Beverages", "beverages.png"),
    ("Personal Care", "personal-care.png"),
    ("Home Care", "home-care.png"),
    ("Breakfast & Instant Food", "breakfast.png"),
    ("Tea, Coffee & Health Drinks", "tea-coffee.png"),
    ("Masala, Oil & Dry Fruits", "masala-oil.png"),
    ("Baby Care", "baby-care.png")
]

products_map = {
    "Fruits & Vegetables": [
        ("Onion", "Fresh Onion"), ("Potato", "Fresh Potato"), ("Tomato", "Fresh Potato"),
        ("Green Chili", "Spicy Green Chili"), ("Lemon", "Lemon"), ("Ginger", "Ginger"),
        ("Coriander", "Fresh Coriander"), ("Garlic", "Garlic"), ("Carrot", "Carrot"),
        ("Apple", "Apple Flavor"), ("Banana", "Banana Robusta")
    ],
    "Dairy & Bakery": [
        ("Milk", "Fresh Milk"), ("Curd", "Fresh Curd"), ("Paneer", "Fresh Paneer"),
        ("Butter", "Salted Butter"), ("Cheese", "Processed Cheese"), ("Bread", "White Bread"),
        ("Eggs", "White Eggs"), ("Yogurt", "Fruit Yogurt"), ("Cream", "Fresh Cream"),
        ("Bun", "Burger Bun")
    ],
    "Staples": [
        ("Atta", "Whole Wheat Atta"), ("Rice", "Basmati Rice"), ("Toor Dal", "Toor Dal"),
        ("Moong Dal", "Moong Dal"), ("Chana Dal", "Chana Dal"), ("Sugar", "Sugar"),
        ("Salt", "Iodized Salt"), ("Besan", "Besan"), ("Maida", "Maida"),
        ("Poha", "Rice Flakes")
    ],
    "Snacks & Branded Foods": [
        ("Biscuits", "Glucose Biscuits"), ("Cookies", "Cookies"), ("Chips", "Potato Chips"),
        ("Namkeen", "Bhujia"), ("Noodles", "Instant Noodles"), ("Pasta", "Pasta"),
        ("Soup", "Instant Pasta"), ("Sauce", "Tomato Ketchup"), ("Jam", "Fruit Jam"),
        ("Popcorn", "Popcorn")
    ],
    "Beverages": [
        ("Cold Drink", "Cola"), ("Juice", "Mango Juice"), ("Soda", "Soda Water"),
        ("Water", "Mineral Water"), ("Energy Drink", "Energy Drink"), ("Lassi", "Lassi"),
        ("Butter Milk", "Chaas"), ("Coconut Water", "Coconut Water"), ("Syrup", "Rose Syrup"),
        ("Squash", "Mango Squash")
    ],
    "Personal Care": [
        ("Soap", "Bathing Soap"), ("Shampoo", "Shampoo"), ("Conditioner", "Conditioner"),
        ("Face Wash", "Face Wash"), ("Toothpaste", "Toothpaste"), ("Toothbrush", "Toothbrush"),
        ("Hair Oil", "Hair Oil"), ("Body Lotion", "Body Lotion"), ("Deodorant", "Deodorant"),
        ("Hand Wash", "Hand Wash")
    ],
    "Home Care": [
        ("Detergent", "Washing Powder"), ("Dish Wash", "Dish Wash Bar"), ("Floor Cleaner", "Floor Cleaner"),
        ("Toilet Cleaner", "Toilet Cleaner"), ("Glass Cleaner", "Glass Cleaner"), ("Air Freshener", "Room Spray"),
        ("Mosquito Repellent", "Mosquito Coil"), ("Shoe Polish", "Shoe Polish"), ("Tissue Paper", "Tissue Paper"),
        ("Garbage Bags", "Garbage Bags")
    ],
    "Breakfast & Instant Food": [
        ("Corn Flakes", "Corn Flakes"), ("Oats", "Masala Oats"), ("Muesli", "Muesli"),
        ("Chocos", "Chocox"), ("Upma Mix", "Instant Upma"), ("Idli Mix", "Instant Idli"),
        ("Dosa Mix", "Instant Dosa"), ("Vermicelli", "Roasted Vermicelli"), ("Macaroni", "Macaroni"),
        ("Pancake Mix", "Pancake Mix")
    ],
    "Tea, Coffee & Health Drinks": [
        ("Tea", "Premium Tea"), ("Green Tea", "Green Tea Bags"), ("Coffee", "Instant Coffee"),
        ("Filter Coffee", "Filter Coffee"), ("Health Drink", "Malt Drink"), ("Glucose Powder", "Glucose D"),
        ("Cocoa Powder", "Cocoa Powder"), ("Tea Bags", "Masala Tea Bags"), ("Coffee Beans", "Coffee Beans"),
        ("Milk Powder", "Dairy Whitener")
    ],
    "Masala, Oil & Dry Fruits": [
        ("Turmeric Powder", "Haldi"), ("Chili Powder", "Mirchi"), ("Coriander Powder", "Dhaniya"),
        ("Garam Masala", "Garam Masala"), ("Cumin Seeds", "Jeera"), ("Mustard Seeds", "Rai"),
        ("Sunflower Oil", "Refined Oil"), ("Mustard Oil", "Kachi Ghani"), ("Cashew", "Kaju"),
        ("Almonds", "Badam")
    ],
    "Baby Care": [
        ("Diapers", "Diapers M"), ("Wipes", "Baby Wipes"), ("Baby Oil", "Massage Oil"),
        ("Baby Powder", "Talc Free"), ("Baby Soap", "Gentle Soap"), ("Baby Shampoo", "No Tears"),
        ("Baby Lotion", "Soft Lotion"), ("Baby Food", "Cereal"), ("Feeding Bottle", "BPA Free"),
        ("Nipple", "Silicone Nipple")
    ]
}

variants_template = [
    ("500g", 0.5), ("1kg", 1.0), ("2kg", 2.0), ("5kg", 5.0)
]
liquid_variants = [
    ("500ml", 0.5), ("1L", 1.0), ("200ml", 0.2)
]
unit_variants = [
    ("1 pc", 1), ("Pack of 3", 3), ("Pack of 6", 6)
]

sql_statements = []

cat_id_counter = 100 # Reset sequences later if needed, starting distinct
prod_id_counter = 1000
var_id_counter = 10000

print("-- ==========================================")
print("-- SEED DATA GENERATED BY AGENT")
print("-- ==========================================")

for cat_name, cat_img in categories:
    cat_id = cat_id_counter
    cat_id_counter += 1

    # Insert Category
    sql = f"INSERT INTO categories (id, name, image_url, active) VALUES ({cat_id}, {escape_sql(cat_name)}, {escape_sql('/images/categories/' + cat_img)}, true) ON CONFLICT (name) DO NOTHING;"
    print(sql)

    # Get products
    prods = products_map.get(cat_name, [])
    for prod_name, prod_desc in prods:
        prod_id = prod_id_counter
        prod_id_counter += 1

        # Insert Product Master
        pm_img = "/images/products/" + prod_name.lower().replace(" ", "-") + ".jpg"
        sql = f"INSERT INTO product_masters (id, name, description, image_url, active, category_id, low_stock_threshold) VALUES ({prod_id}, {escape_sql(prod_name)}, {escape_sql(prod_desc)}, {escape_sql(pm_img)}, true, {cat_id}, 5);"
        print(sql)

        # Determine variant type
        v_template = variants_template
        if cat_name in ["Beverages", "Masala, Oil & Dry Fruits"] and "Oil" in prod_name or "Drink" in prod_name or "Juice" in prod_name:
            v_template = liquid_variants
        elif cat_name in ["Personal Care", "Home Care", "Baby Care", "Snacks & Branded Foods"]:
            v_template = unit_variants

        # Generate 2-4 variants per product
        num_variants = random.randint(2, 4)
        for i in range(num_variants):
            var_id = var_id_counter
            var_id_counter += 1

            v_name, multiplier = v_template[i % len(v_template)]
            variant_full_name = f"{prod_name} {v_name}"

            base_price = random.randint(20, 500)
            mrp = int(base_price * multiplier)
            if mrp < 10: mrp = 10

            discount = random.choice([0, 5, 10, 15, 20])
            stock = random.randint(0, 100) # Some 0 for out of stock testing

            # Ensure "unit" is string
            unit_str = v_name

            sql = f"INSERT INTO product_variants (id, name, mrp, discount_percent, unit, image_url, stock, product_master_id) VALUES ({var_id}, {escape_sql(variant_full_name)}, {mrp}.00, {discount}, {escape_sql(unit_str)}, {escape_sql(pm_img)}, {stock}, {prod_id});"
            print(sql)

print("")
print(f"ALTER SEQUENCE categories_id_seq RESTART WITH {cat_id_counter};")
print(f"ALTER SEQUENCE product_masters_id_seq RESTART WITH {prod_id_counter};")
print(f"ALTER SEQUENCE product_variants_id_seq RESTART WITH {var_id_counter};")
