INSERT INTO categories (name, slug, image_url) VALUES
                                                   ('Fruits', 'fruits', 'categories/fruits.webp'),
                                                   ('Vegetables', 'vegetables', 'categories/vegetables.webp'),
                                                   ('Dairy & Eggs', 'dairy-eggs', 'categories/dairy-eggs.webp'),
                                                   ('Bakery', 'bakery', 'categories/bakery.webp'),
                                                   ('Meat & Seafood', 'meat-seafood', 'categories/meat-seafood.webp'),
                                                   ('Rice, Atta & Pulses', 'rice-atta-pulses', 'categories/rice-atta-pulses.webp'),
                                                   ('Oil, Ghee & Masala', 'oil-ghee-masala', 'categories/oil-ghee-masala.webp'),
                                                   ('Snacks & Biscuits', 'snacks-biscuits', 'categories/snacks-biscuits.webp'),
                                                   ('Beverages', 'beverages', 'categories/beverages.webp'),
                                                   ('Frozen Foods', 'frozen-foods', 'categories/frozen-foods.webp'),
                                                   ('Ready to Cook', 'ready-to-cook', 'categories/ready-to-cook.webp'),
                                                   ('Breakfast & Cereals', 'breakfast-cereals', 'categories/breakfast-cereals.webp'),
                                                   ('Sauces, Spreads & Pickles', 'sauces-spreads-pickles', 'categories/sauces-spreads-pickles.webp'),
                                                   ('Personal Care', 'personal-care', 'categories/personal-care.webp'),
                                                   ('Household Essentials', 'household-essentials', 'categories/household-essentials.webp');
