INSERT INTO products (category_id, name, slug, base_image_url, description, is_active)
VALUES
((SELECT id FROM categories WHERE slug = 'fruits'), 'Banana', 'banana', 'products/fruits/banana.webp', 'Fresh bananas, naturally sweet and energy rich.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Apple', 'apple', 'products/fruits/apple.webp', 'Crisp, juicy apples for everyday snacking.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Mango', 'mango', 'products/fruits/mango.webp', 'Seasonal mangoes with rich aroma and sweetness.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Orange', 'orange', 'products/fruits/orange.webp', 'Juicy oranges packed with vitamin C.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Grapes', 'grapes', 'products/fruits/grapes.webp', 'Fresh seedless grapes, perfect for snacking.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Pomegranate', 'pomegranate', 'products/fruits/pomegranate.webp', 'Ruby pomegranates with sweet-tart arils.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Papaya', 'papaya', 'products/fruits/papaya.webp', 'Ripe papaya, great for digestion.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Watermelon', 'watermelon', 'products/fruits/watermelon.webp', 'Refreshing watermelon, ideal for summers.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Pineapple', 'pineapple', 'products/fruits/pineapple.webp', 'Tangy pineapple for juices and desserts.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Guava', 'guava', 'products/fruits/guava.webp', 'Fresh guava, high in vitamin C and fiber.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Kiwi', 'kiwi', 'products/fruits/kiwi.webp', 'Zesty kiwi fruit for smoothies and salads.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Strawberry', 'strawberry', 'products/fruits/strawberry.webp', 'Sweet strawberries for desserts and shakes.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Custard Apple', 'custard-apple', 'products/fruits/custard-apple.webp', 'Creamy custard apples with rich flavor.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Pear', 'pear', 'products/fruits/pear.webp', 'Crisp pears with mild sweetness.', true),
((SELECT id FROM categories WHERE slug = 'fruits'), 'Chikoo (Sapota)', 'chikoo-sapota', 'products/fruits/chikoo-sapota.webp', 'Naturally sweet chikoo (sapota).', true),

((SELECT id FROM categories WHERE slug = 'vegetables'), 'Onion', 'onion', 'products/vegetables/onion.webp', 'Fresh onions for everyday cooking.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Potato', 'potato', 'products/vegetables/potato.webp', 'Fresh potatoes for curries and fries.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Tomato', 'tomato', 'products/vegetables/tomato.webp', 'Juicy tomatoes for gravies and salads.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Carrot', 'carrot', 'products/vegetables/carrot.webp', 'Crunchy carrots for salads and cooking.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Cucumber', 'cucumber', 'products/vegetables/cucumber.webp', 'Fresh cucumbers for salads and raita.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Green Chilli', 'green-chilli', 'products/vegetables/green-chilli.webp', 'Spicy green chillies for tempering.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Ginger', 'ginger', 'products/vegetables/ginger.webp', 'Fresh ginger with strong aroma.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Garlic', 'garlic', 'products/vegetables/garlic.webp', 'Fresh garlic pods for cooking.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Spinach', 'spinach', 'products/vegetables/spinach.webp', 'Leafy spinach, rich in iron.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Cauliflower', 'cauliflower', 'products/vegetables/cauliflower.webp', 'Fresh cauliflower florets.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Cabbage', 'cabbage', 'products/vegetables/cabbage.webp', 'Fresh cabbage for stir fries.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Capsicum', 'capsicum', 'products/vegetables/capsicum.webp', 'Green capsicum for salads and cooking.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Brinjal', 'brinjal', 'products/vegetables/brinjal.webp', 'Fresh brinjal (eggplant).', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Lady Finger (Okra)', 'lady-finger-okra', 'products/vegetables/lady-finger-okra.webp', 'Tender okra for fries and curries.', true),
((SELECT id FROM categories WHERE slug = 'vegetables'), 'Beetroot', 'beetroot', 'products/vegetables/beetroot.webp', 'Fresh beetroot for salads and juice.', true),

((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Toned Milk', 'toned-milk', 'products/dairy-eggs/toned-milk.webp', 'Daily toned milk for tea and drinking.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Full Cream Milk', 'full-cream-milk', 'products/dairy-eggs/full-cream-milk.webp', 'Creamy milk with richer taste.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Curd (Dahi)', 'curd-dahi', 'products/dairy-eggs/curd-dahi.webp', 'Fresh curd for meals and raita.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Paneer', 'paneer', 'products/dairy-eggs/paneer.webp', 'Fresh paneer blocks for curries.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Butter', 'butter', 'products/dairy-eggs/butter.webp', 'Salted butter for toast and cooking.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Ghee', 'ghee', 'products/dairy-eggs/ghee.webp', 'Pure ghee for cooking and sweets.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Cheese Slices', 'cheese-slices', 'products/dairy-eggs/cheese-slices.webp', 'Processed cheese slices for sandwiches.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Cheese Block', 'cheese-block', 'products/dairy-eggs/cheese-block.webp', 'Cheese block for grating and cooking.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Eggs (White)', 'eggs-white', 'products/dairy-eggs/eggs-white.webp', 'Farm fresh white eggs.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Eggs (Brown)', 'eggs-brown', 'products/dairy-eggs/eggs-brown.webp', 'Farm fresh brown eggs.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Buttermilk (Chaas)', 'buttermilk-chaas', 'products/dairy-eggs/buttermilk-chaas.webp', 'Refreshing spiced buttermilk.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Lassi', 'lassi', 'products/dairy-eggs/lassi.webp', 'Sweet lassi, chilled and refreshing.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Fresh Cream', 'fresh-cream', 'products/dairy-eggs/fresh-cream.webp', 'Fresh cream for cooking and desserts.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Yogurt Cup', 'yogurt-cup', 'products/dairy-eggs/yogurt-cup.webp', 'Flavoured yogurt cup.', true),
((SELECT id FROM categories WHERE slug = 'dairy-eggs'), 'Flavoured Milk', 'flavoured-milk', 'products/dairy-eggs/flavoured-milk.webp', 'Ready-to-drink flavoured milk.', true),

((SELECT id FROM categories WHERE slug = 'bakery'), 'White Bread', 'white-bread', 'products/bakery/white-bread.webp', 'Soft white bread loaf.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Whole Wheat Bread', 'whole-wheat-bread', 'products/bakery/whole-wheat-bread.webp', 'Healthy whole wheat bread.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Brown Bread', 'brown-bread', 'products/bakery/brown-bread.webp', 'Fibre-rich brown bread loaf.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Burger Buns', 'burger-buns', 'products/bakery/burger-buns.webp', 'Soft buns for burgers.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Pav (Ladi Pav)', 'pav-ladi-pav', 'products/bakery/pav-ladi-pav.webp', 'Mumbai-style ladi pav.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Milk Bread', 'milk-bread', 'products/bakery/milk-bread.webp', 'Soft milk bread loaf.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Multigrain Bread', 'multigrain-bread', 'products/bakery/multigrain-bread.webp', 'Bread with mixed grains and seeds.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Eggless Cake', 'eggless-cake', 'products/bakery/eggless-cake.webp', 'Fresh eggless cake slice.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Rusk', 'rusk', 'products/bakery/rusk.webp', 'Crunchy toasted rusk.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Muffins', 'muffins', 'products/bakery/muffins.webp', 'Soft muffins for snacking.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Croissant', 'croissant', 'products/bakery/croissant.webp', 'Flaky croissant pastry.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Garlic Bread', 'garlic-bread', 'products/bakery/garlic-bread.webp', 'Garlic bread for baking.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Pita Bread', 'pita-bread', 'products/bakery/pita-bread.webp', 'Pita bread for wraps.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Dinner Rolls', 'dinner-rolls', 'products/bakery/dinner-rolls.webp', 'Soft dinner rolls.', true),
((SELECT id FROM categories WHERE slug = 'bakery'), 'Sandwich Bread', 'sandwich-bread', 'products/bakery/sandwich-bread.webp', 'Bread loaf ideal for sandwiches.', true),

((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken (Curry Cut)', 'chicken-curry-cut', 'products/meat-seafood/chicken-curry-cut.webp', 'Fresh chicken curry cut pieces.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Breast', 'chicken-breast', 'products/meat-seafood/chicken-breast.webp', 'Boneless chicken breast.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Mince', 'chicken-mince', 'products/meat-seafood/chicken-mince.webp', 'Fresh chicken mince.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Mutton (Curry Cut)', 'mutton-curry-cut', 'products/meat-seafood/mutton-curry-cut.webp', 'Fresh mutton curry cut.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Fish (Rohu)', 'fish-rohu', 'products/meat-seafood/fish-rohu.webp', 'Fresh rohu fish pieces.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Fish (Pomfret)', 'fish-pomfret', 'products/meat-seafood/fish-pomfret.webp', 'Fresh pomfret fish.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Prawns', 'prawns', 'products/meat-seafood/prawns.webp', 'Cleaned prawns for curries.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Eggs (Boiled)', 'eggs-boiled', 'products/meat-seafood/eggs-boiled.webp', 'Ready-to-eat boiled eggs.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Sausages', 'chicken-sausages', 'products/meat-seafood/chicken-sausages.webp', 'Ready-to-cook chicken sausages.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Nuggets', 'chicken-nuggets', 'products/meat-seafood/chicken-nuggets.webp', 'Frozen chicken nuggets.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Fish Fingers', 'fish-fingers', 'products/meat-seafood/fish-fingers.webp', 'Frozen fish fingers.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Wings', 'chicken-wings', 'products/meat-seafood/chicken-wings.webp', 'Fresh chicken wings.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Chicken Drumsticks', 'chicken-drumsticks', 'products/meat-seafood/chicken-drumsticks.webp', 'Fresh chicken drumsticks.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Mutton Keema', 'mutton-keema', 'products/meat-seafood/mutton-keema.webp', 'Fresh mutton mince.', true),
((SELECT id FROM categories WHERE slug = 'meat-seafood'), 'Salmon Fillet', 'salmon-fillet', 'products/meat-seafood/salmon-fillet.webp', 'Fresh salmon fillet.', true),

((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Basmati Rice', 'basmati-rice', 'products/rice-atta-pulses/basmati-rice.webp', 'Aromatic basmati rice for biryani.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Sona Masoori Rice', 'sona-masoori-rice', 'products/rice-atta-pulses/sona-masoori-rice.webp', 'Everyday sona masoori rice.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Wheat Atta', 'wheat-atta', 'products/rice-atta-pulses/wheat-atta.webp', 'Whole wheat flour for chapati.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Multigrain Atta', 'multigrain-atta', 'products/rice-atta-pulses/multigrain-atta.webp', 'Atta with multiple grains.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Toor Dal', 'toor-dal', 'products/rice-atta-pulses/toor-dal.webp', 'Premium toor dal for sambar.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Moong Dal', 'moong-dal', 'products/rice-atta-pulses/moong-dal.webp', 'Washed moong dal.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Chana Dal', 'chana-dal', 'products/rice-atta-pulses/chana-dal.webp', 'Chana dal for curries and snacks.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Masoor Dal', 'masoor-dal', 'products/rice-atta-pulses/masoor-dal.webp', 'Red lentils for quick cooking.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Urad Dal', 'urad-dal', 'products/rice-atta-pulses/urad-dal.webp', 'Urad dal for dosa/idli batter.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Rajma', 'rajma', 'products/rice-atta-pulses/rajma.webp', 'Red kidney beans.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Chole (Kabuli Chana)', 'chole-kabuli-chana', 'products/rice-atta-pulses/chole-kabuli-chana.webp', 'Kabuli chana for chole.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Kala Chana', 'kala-chana', 'products/rice-atta-pulses/kala-chana.webp', 'Black chickpeas.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Poha', 'poha', 'products/rice-atta-pulses/poha.webp', 'Flattened rice for breakfast.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Suji (Rava)', 'suji-rava', 'products/rice-atta-pulses/suji-rava.webp', 'Semolina for upma and halwa.', true),
((SELECT id FROM categories WHERE slug = 'rice-atta-pulses'), 'Besan', 'besan', 'products/rice-atta-pulses/besan.webp', 'Gram flour for snacks.', true),

((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Sunflower Oil', 'sunflower-oil', 'products/oil-ghee-masala/sunflower-oil.webp', 'Refined sunflower cooking oil.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Mustard Oil', 'mustard-oil', 'products/oil-ghee-masala/mustard-oil.webp', 'Kachi ghani mustard oil.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Groundnut Oil', 'groundnut-oil', 'products/oil-ghee-masala/groundnut-oil.webp', 'Refined groundnut oil.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Olive Oil', 'olive-oil', 'products/oil-ghee-masala/olive-oil.webp', 'Extra light olive oil for cooking.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Cow Ghee', 'cow-ghee', 'products/oil-ghee-masala/cow-ghee.webp', 'Pure cow ghee.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Turmeric Powder', 'turmeric-powder', 'products/oil-ghee-masala/turmeric-powder.webp', 'Haldi powder for daily cooking.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Red Chilli Powder', 'red-chilli-powder', 'products/oil-ghee-masala/red-chilli-powder.webp', 'Spicy red chilli powder.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Coriander Powder', 'coriander-powder', 'products/oil-ghee-masala/coriander-powder.webp', 'Dhaniya powder.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Garam Masala', 'garam-masala', 'products/oil-ghee-masala/garam-masala.webp', 'Blend of aromatic spices.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Cumin Seeds', 'cumin-seeds', 'products/oil-ghee-masala/cumin-seeds.webp', 'Jeera for tempering.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Mustard Seeds', 'mustard-seeds', 'products/oil-ghee-masala/mustard-seeds.webp', 'Rai seeds for tadka.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Black Pepper', 'black-pepper', 'products/oil-ghee-masala/black-pepper.webp', 'Whole black peppercorns.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Cardamom', 'cardamom', 'products/oil-ghee-masala/cardamom.webp', 'Green cardamom pods.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Cloves', 'cloves', 'products/oil-ghee-masala/cloves.webp', 'Whole cloves.', true),
((SELECT id FROM categories WHERE slug = 'oil-ghee-masala'), 'Bay Leaf', 'bay-leaf', 'products/oil-ghee-masala/bay-leaf.webp', 'Tej patta for flavour.', true),

((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Glucose Biscuits', 'glucose-biscuits', 'products/snacks-biscuits/glucose-biscuits.webp', 'Everyday glucose biscuits.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Butter Cookies', 'butter-cookies', 'products/snacks-biscuits/butter-cookies.webp', 'Crispy butter cookies.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Potato Chips', 'potato-chips', 'products/snacks-biscuits/potato-chips.webp', 'Crunchy salted chips.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Banana Chips', 'banana-chips', 'products/snacks-biscuits/banana-chips.webp', 'Kerala-style banana chips.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Bhujia Sev', 'bhujia-sev', 'products/snacks-biscuits/bhujia-sev.webp', 'Spicy bhujia sev.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Mixture Namkeen', 'mixture-namkeen', 'products/snacks-biscuits/mixture-namkeen.webp', 'Mixed namkeen.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Popcorn', 'popcorn', 'products/snacks-biscuits/popcorn.webp', 'Butter flavoured popcorn.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Roasted Peanuts', 'roasted-peanuts', 'products/snacks-biscuits/roasted-peanuts.webp', 'Roasted peanuts for snacking.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Chocolates', 'chocolates', 'products/snacks-biscuits/chocolates.webp', 'Assorted chocolates.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Energy Bars', 'energy-bars', 'products/snacks-biscuits/energy-bars.webp', 'Nutri energy bars.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Rusks', 'rusks', 'products/snacks-biscuits/rusks.webp', 'Crispy rusks.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Cream Biscuits', 'cream-biscuits', 'products/snacks-biscuits/cream-biscuits.webp', 'Cream-filled biscuits.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Salted Nachos', 'salted-nachos', 'products/snacks-biscuits/salted-nachos.webp', 'Corn nachos.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Chakli', 'chakli', 'products/snacks-biscuits/chakli.webp', 'Crunchy chakli snacks.', true),
((SELECT id FROM categories WHERE slug = 'snacks-biscuits'), 'Murukku', 'murukku', 'products/snacks-biscuits/murukku.webp', 'South Indian murukku.', true),

((SELECT id FROM categories WHERE slug = 'beverages'), 'Cola Soft Drink', 'cola-soft-drink', 'products/beverages/cola-soft-drink.webp', 'Sparkling cola drink.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Lemon Soda', 'lemon-soda', 'products/beverages/lemon-soda.webp', 'Refreshing lemon soda.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Orange Juice', 'orange-juice', 'products/beverages/orange-juice.webp', 'Packed orange juice.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Mango Drink', 'mango-drink', 'products/beverages/mango-drink.webp', 'Packed mango drink.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Mineral Water', 'mineral-water', 'products/beverages/mineral-water.webp', 'Packaged drinking water.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Energy Drink', 'energy-drink', 'products/beverages/energy-drink.webp', 'Caffeinated energy drink.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Coconut Water', 'coconut-water', 'products/beverages/coconut-water.webp', 'Natural coconut water.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Spiced Buttermilk', 'spiced-buttermilk', 'products/beverages/spiced-buttermilk.webp', 'Spiced buttermilk.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Cold Coffee', 'cold-coffee', 'products/beverages/cold-coffee.webp', 'Ready-to-drink cold coffee.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Iced Tea', 'iced-tea', 'products/beverages/iced-tea.webp', 'Flavoured iced tea.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Instant Coffee', 'instant-coffee', 'products/beverages/instant-coffee.webp', 'Instant coffee powder.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Assam Tea', 'assam-tea', 'products/beverages/assam-tea.webp', 'Assam tea for daily brewing.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Green Tea Bags', 'green-tea-bags', 'products/beverages/green-tea-bags.webp', 'Green tea bags.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Chocolate Drink', 'chocolate-drink', 'products/beverages/chocolate-drink.webp', 'Chocolate flavoured drink.', true),
((SELECT id FROM categories WHERE slug = 'beverages'), 'Soda Water', 'soda-water', 'products/beverages/soda-water.webp', 'Club soda water.', true),

((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Peas', 'frozen-peas', 'products/frozen-foods/frozen-peas.webp', 'Frozen green peas.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Corn', 'frozen-corn', 'products/frozen-foods/frozen-corn.webp', 'Frozen sweet corn.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen French Fries', 'frozen-french-fries', 'products/frozen-foods/frozen-french-fries.webp', 'Crispy frozen fries.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Veg Nuggets', 'frozen-veg-nuggets', 'products/frozen-foods/frozen-veg-nuggets.webp', 'Frozen veg nuggets.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Paratha', 'frozen-paratha', 'products/frozen-foods/frozen-paratha.webp', 'Ready-to-cook frozen paratha.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Samosa', 'frozen-samosa', 'products/frozen-foods/frozen-samosa.webp', 'Frozen samosa.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Momos', 'frozen-momos', 'products/frozen-foods/frozen-momos.webp', 'Frozen veg momos.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Mixed Veg', 'frozen-mixed-veg', 'products/frozen-foods/frozen-mixed-veg.webp', 'Frozen mixed vegetables.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Fish Fingers', 'frozen-fish-fingers', 'products/frozen-foods/frozen-fish-fingers.webp', 'Frozen fish fingers.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Chicken Nuggets', 'frozen-chicken-nuggets', 'products/frozen-foods/frozen-chicken-nuggets.webp', 'Frozen chicken nuggets.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Pizza Base', 'frozen-pizza-base', 'products/frozen-foods/frozen-pizza-base.webp', 'Frozen pizza base.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Idli', 'frozen-idli', 'products/frozen-foods/frozen-idli.webp', 'Frozen idli.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Dosa', 'frozen-dosa', 'products/frozen-foods/frozen-dosa.webp', 'Frozen dosa.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Frozen Aloo Tikki', 'frozen-aloo-tikki', 'products/frozen-foods/frozen-aloo-tikki.webp', 'Frozen aloo tikki.', true),
((SELECT id FROM categories WHERE slug = 'frozen-foods'), 'Ice Cream (Tub)', 'ice-cream-tub', 'products/frozen-foods/ice-cream-tub.webp', 'Ice cream tub.', true),

((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Upma Mix', 'instant-upma-mix', 'products/ready-to-cook/instant-upma-mix.webp', 'Ready upma mix.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Poha Mix', 'instant-poha-mix', 'products/ready-to-cook/instant-poha-mix.webp', 'Ready poha mix.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Idli Dosa Batter', 'idli-dosa-batter', 'products/ready-to-cook/idli-dosa-batter.webp', 'Fresh idli dosa batter.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Ready Paratha', 'ready-paratha', 'products/ready-to-cook/ready-paratha.webp', 'Ready paratha for quick meals.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Noodles', 'instant-noodles', 'products/ready-to-cook/instant-noodles.webp', 'Instant noodles.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Pasta', 'pasta', 'products/ready-to-cook/pasta.webp', 'Dry pasta.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Soup', 'instant-soup', 'products/ready-to-cook/instant-soup.webp', 'Instant soup packets.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Frozen Roti', 'frozen-roti', 'products/ready-to-cook/frozen-roti.webp', 'Ready roti.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Ready Dosa', 'ready-dosa', 'products/ready-to-cook/ready-dosa.webp', 'Ready-to-eat dosa.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Ready Sambar', 'ready-sambar', 'products/ready-to-cook/ready-sambar.webp', 'Ready sambar pack.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Pav Bhaji', 'instant-pav-bhaji', 'products/ready-to-cook/instant-pav-bhaji.webp', 'Instant pav bhaji mix.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Chole', 'instant-chole', 'products/ready-to-cook/instant-chole.webp', 'Instant chole pack.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Rajma', 'instant-rajma', 'products/ready-to-cook/instant-rajma.webp', 'Ready rajma curry.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Ready Mix Dhokla', 'ready-mix-dhokla', 'products/ready-to-cook/ready-mix-dhokla.webp', 'Instant dhokla mix.', true),
((SELECT id FROM categories WHERE slug = 'ready-to-cook'), 'Instant Idli Mix', 'instant-idli-mix', 'products/ready-to-cook/instant-idli-mix.webp', 'Instant idli mix.', true),

((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Corn Flakes', 'corn-flakes', 'products/breakfast-cereals/corn-flakes.webp', 'Classic corn flakes.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Rolled Oats', 'rolled-oats', 'products/breakfast-cereals/rolled-oats.webp', 'Rolled oats.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Muesli', 'muesli', 'products/breakfast-cereals/muesli.webp', 'Fruits and nuts muesli.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Chocos', 'chocos', 'products/breakfast-cereals/chocos.webp', 'Chocolate cereal for kids.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Honey', 'honey', 'products/breakfast-cereals/honey.webp', 'Pure honey.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Peanut Butter', 'peanut-butter', 'products/breakfast-cereals/peanut-butter.webp', 'Creamy peanut butter.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Fruit Jam', 'fruit-jam', 'products/breakfast-cereals/fruit-jam.webp', 'Fruit jam.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Choco Spread', 'choco-spread', 'products/breakfast-cereals/choco-spread.webp', 'Chocolate spread.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Instant Idli Mix', 'instant-idli-mix-2', 'products/breakfast-cereals/instant-idli-mix.webp', 'Instant idli mix.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Instant Dosa Mix', 'instant-dosa-mix', 'products/breakfast-cereals/instant-dosa-mix.webp', 'Instant dosa mix.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Instant Upma Mix', 'instant-upma-mix-2', 'products/breakfast-cereals/instant-upma-mix.webp', 'Instant upma mix.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Poha', 'poha', 'products/breakfast-cereals/poha.webp', 'Flattened rice poha.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Vermicelli', 'vermicelli', 'products/breakfast-cereals/vermicelli.webp', 'Roasted vermicelli.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Ragi Flour', 'ragi-flour', 'products/breakfast-cereals/ragi-flour.webp', 'Ragi flour for porridge and dosa.', true),
((SELECT id FROM categories WHERE slug = 'breakfast-cereals'), 'Sooji', 'sooji', 'products/breakfast-cereals/sooji.webp', 'Semolina for upma.', true),

((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Tomato Ketchup', 'tomato-ketchup', 'products/sauces-spreads-pickles/tomato-ketchup.webp', 'Tomato ketchup.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Mayonnaise', 'mayonnaise', 'products/sauces-spreads-pickles/mayonnaise.webp', 'Creamy mayonnaise.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Green Chilli Sauce', 'green-chilli-sauce', 'products/sauces-spreads-pickles/green-chilli-sauce.webp', 'Spicy green chilli sauce.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Soy Sauce', 'soy-sauce', 'products/sauces-spreads-pickles/soy-sauce.webp', 'Soy sauce for Chinese cooking.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Vinegar', 'vinegar', 'products/sauces-spreads-pickles/vinegar.webp', 'Cooking vinegar.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Mixed Fruit Jam', 'mixed-fruit-jam', 'products/sauces-spreads-pickles/mixed-fruit-jam.webp', 'Mixed fruit jam.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Peanut Butter', 'peanut-butter-2', 'products/sauces-spreads-pickles/peanut-butter.webp', 'Peanut butter spread.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Honey', 'honey-2', 'products/sauces-spreads-pickles/honey.webp', 'Pure honey.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Mango Pickle', 'mango-pickle', 'products/sauces-spreads-pickles/mango-pickle.webp', 'Traditional mango pickle.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Lime Pickle', 'lime-pickle', 'products/sauces-spreads-pickles/lime-pickle.webp', 'Tangy lime pickle.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Chilli Pickle', 'chilli-pickle', 'products/sauces-spreads-pickles/chilli-pickle.webp', 'Spicy chilli pickle.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Chocolate Spread', 'chocolate-spread', 'products/sauces-spreads-pickles/chocolate-spread.webp', 'Chocolate spread.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Chutney', 'chutney', 'products/sauces-spreads-pickles/chutney.webp', 'Ready chutney.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Pizza Sauce', 'pizza-sauce', 'products/sauces-spreads-pickles/pizza-sauce.webp', 'Pizza and pasta sauce.', true),
((SELECT id FROM categories WHERE slug = 'sauces-spreads-pickles'), 'Sandwich Spread', 'sandwich-spread', 'products/sauces-spreads-pickles/sandwich-spread.webp', 'Sandwich spread.', true),

((SELECT id FROM categories WHERE slug = 'personal-care'), 'Bath Soap', 'bath-soap', 'products/personal-care/bath-soap.webp', 'Bathing soap bar.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Shampoo', 'shampoo', 'products/personal-care/shampoo.webp', 'Daily use shampoo.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Conditioner', 'conditioner', 'products/personal-care/conditioner.webp', 'Hair conditioner.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Face Wash', 'face-wash', 'products/personal-care/face-wash.webp', 'Face wash.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Body Lotion', 'body-lotion', 'products/personal-care/body-lotion.webp', 'Moisturizing body lotion.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Toothpaste', 'toothpaste', 'products/personal-care/toothpaste.webp', 'Toothpaste for daily brushing.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Toothbrush', 'toothbrush', 'products/personal-care/toothbrush.webp', 'Toothbrush.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Hand Wash', 'hand-wash', 'products/personal-care/hand-wash.webp', 'Liquid hand wash.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Sanitary Napkins', 'sanitary-napkins', 'products/personal-care/sanitary-napkins.webp', 'Sanitary napkins.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Deodorant', 'deodorant', 'products/personal-care/deodorant.webp', 'Deodorant spray.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Shaving Cream', 'shaving-cream', 'products/personal-care/shaving-cream.webp', 'Shaving cream.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Razor', 'razor', 'products/personal-care/razor.webp', 'Disposable razor.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Hair Oil', 'hair-oil', 'products/personal-care/hair-oil.webp', 'Hair oil.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Face Cream', 'face-cream', 'products/personal-care/face-cream.webp', 'Face cream.', true),
((SELECT id FROM categories WHERE slug = 'personal-care'), 'Talc Powder', 'talc-powder', 'products/personal-care/talc-powder.webp', 'Talc powder.', true),

((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Detergent Powder', 'detergent-powder', 'products/household-essentials/detergent-powder.webp', 'Laundry detergent powder.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Dishwash Liquid', 'dishwash-liquid', 'products/household-essentials/dishwash-liquid.webp', 'Dishwash liquid.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Dishwash Bar', 'dishwash-bar', 'products/household-essentials/dishwash-bar.webp', 'Dishwash bar.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Floor Cleaner', 'floor-cleaner', 'products/household-essentials/floor-cleaner.webp', 'Floor cleaning liquid.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Toilet Cleaner', 'toilet-cleaner', 'products/household-essentials/toilet-cleaner.webp', 'Toilet cleaner.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Glass Cleaner', 'glass-cleaner', 'products/household-essentials/glass-cleaner.webp', 'Glass cleaner spray.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Room Freshener', 'room-freshener', 'products/household-essentials/room-freshener.webp', 'Room freshener spray.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Garbage Bags', 'garbage-bags', 'products/household-essentials/garbage-bags.webp', 'Garbage disposal bags.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Aluminium Foil', 'aluminium-foil', 'products/household-essentials/aluminium-foil.webp', 'Aluminium foil roll.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Cling Film', 'cling-film', 'products/household-essentials/cling-film.webp', 'Cling film roll.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Tissue Paper', 'tissue-paper', 'products/household-essentials/tissue-paper.webp', 'Tissue paper.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Kitchen Towels', 'kitchen-towels', 'products/household-essentials/kitchen-towels.webp', 'Kitchen paper towels.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Toothpick', 'toothpick', 'products/household-essentials/toothpick.webp', 'Wooden toothpicks.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Matchbox', 'matchbox', 'products/household-essentials/matchbox.webp', 'Matchbox pack.', true),
((SELECT id FROM categories WHERE slug = 'household-essentials'), 'Mosquito Repellent', 'mosquito-repellent', 'products/household-essentials/mosquito-repellent.webp', 'Mosquito repellent.', true);

INSERT INTO product_variants (product_id, variant_name, price, stock, sku, is_active)
VALUES
((SELECT id FROM products WHERE slug='banana'), '500g', 30.00, 180, 'FRU-BAN-500G', true),
((SELECT id FROM products WHERE slug='banana'), '1kg', 55.00, 210, 'FRU-BAN-1KG', true),
((SELECT id FROM products WHERE slug='banana'), '2kg', 105.00, 120, 'FRU-BAN-2KG', true),

((SELECT id FROM products WHERE slug='apple'), '500g', 95.00, 160, 'FRU-APP-500G', true),
((SELECT id FROM products WHERE slug='apple'), '1kg', 180.00, 140, 'FRU-APP-1KG', true),

((SELECT id FROM products WHERE slug='mango'), '1kg', 160.00, 120, 'FRU-MNG-1KG', true),
((SELECT id FROM products WHERE slug='mango'), '2kg', 310.00, 80, 'FRU-MNG-2KG', true),

((SELECT id FROM products WHERE slug='orange'), '500g', 65.00, 140, 'FRU-ORG-500G', true),
((SELECT id FROM products WHERE slug='orange'), '1kg', 125.00, 120, 'FRU-ORG-1KG', true),

((SELECT id FROM products WHERE slug='grapes'), '250g', 55.00, 90, 'FRU-GRP-250G', true),
((SELECT id FROM products WHERE slug='grapes'), '500g', 105.00, 120, 'FRU-GRP-500G', true),

((SELECT id FROM products WHERE slug='pomegranate'), '500g', 110.00, 90, 'FRU-POM-500G', true),
((SELECT id FROM products WHERE slug='pomegranate'), '1kg', 210.00, 80, 'FRU-POM-1KG', true),

((SELECT id FROM products WHERE slug='papaya'), '1pc', 55.00, 140, 'FRU-PAP-1PC', true),
((SELECT id FROM products WHERE slug='papaya'), '2pc', 100.00, 80, 'FRU-PAP-2PC', true),

((SELECT id FROM products WHERE slug='watermelon'), '1pc', 90.00, 70, 'FRU-WAT-1PC', true),
((SELECT id FROM products WHERE slug='watermelon'), '2pc', 170.00, 50, 'FRU-WAT-2PC', true),

((SELECT id FROM products WHERE slug='pineapple'), '1pc', 80.00, 90, 'FRU-PIN-1PC', true),
((SELECT id FROM products WHERE slug='pineapple'), '2pc', 150.00, 70, 'FRU-PIN-2PC', true),

((SELECT id FROM products WHERE slug='guava'), '500g', 60.00, 130, 'FRU-GUV-500G', true),
((SELECT id FROM products WHERE slug='guava'), '1kg', 110.00, 90, 'FRU-GUV-1KG', true),

((SELECT id FROM products WHERE slug='kiwi'), '3pcs', 120.00, 60, 'FRU-KIW-3PC', true),
((SELECT id FROM products WHERE slug='kiwi'), '6pcs', 230.00, 50, 'FRU-KIW-6PC', true),

((SELECT id FROM products WHERE slug='strawberry'), '200g', 110.00, 60, 'FRU-STR-200G', true),
((SELECT id FROM products WHERE slug='strawberry'), '400g', 210.00, 50, 'FRU-STR-400G', true),

((SELECT id FROM products WHERE slug='custard-apple'), '500g', 95.00, 50, 'FRU-CUS-500G', true),
((SELECT id FROM products WHERE slug='custard-apple'), '1kg', 180.00, 40, 'FRU-CUS-1KG', true),

((SELECT id FROM products WHERE slug='pear'), '500g', 85.00, 60, 'FRU-PEA-500G', true),
((SELECT id FROM products WHERE slug='pear'), '1kg', 160.00, 50, 'FRU-PEA-1KG', true),

((SELECT id FROM products WHERE slug='chikoo-sapota'), '500g', 55.00, 80, 'FRU-CHK-500G', true),
((SELECT id FROM products WHERE slug='chikoo-sapota'), '1kg', 105.00, 70, 'FRU-CHK-1KG', true),

((SELECT id FROM products WHERE slug='onion'), '500g', 22.00, 240, 'VEG-ONI-500G', true),
((SELECT id FROM products WHERE slug='onion'), '1kg', 40.00, 280, 'VEG-ONI-1KG', true),
((SELECT id FROM products WHERE slug='onion'), '2kg', 75.00, 180, 'VEG-ONI-2KG', true),

((SELECT id FROM products WHERE slug='potato'), '1kg', 30.00, 280, 'VEG-POT-1KG', true),
((SELECT id FROM products WHERE slug='potato'), '2kg', 55.00, 240, 'VEG-POT-2KG', true),

((SELECT id FROM products WHERE slug='tomato'), '500g', 18.00, 220, 'VEG-TOM-500G', true),
((SELECT id FROM products WHERE slug='tomato'), '1kg', 34.00, 200, 'VEG-TOM-1KG', true),

((SELECT id FROM products WHERE slug='carrot'), '500g', 35.00, 180, 'VEG-CAR-500G', true),
((SELECT id FROM products WHERE slug='carrot'), '1kg', 65.00, 160, 'VEG-CAR-1KG', true),

((SELECT id FROM products WHERE slug='cucumber'), '500g', 25.00, 180, 'VEG-CUC-500G', true),
((SELECT id FROM products WHERE slug='cucumber'), '1kg', 45.00, 140, 'VEG-CUC-1KG', true),

((SELECT id FROM products WHERE slug='green-chilli'), '100g', 10.00, 220, 'VEG-CHI-100G', true),
((SELECT id FROM products WHERE slug='green-chilli'), '250g', 22.00, 180, 'VEG-CHI-250G', true),

((SELECT id FROM products WHERE slug='ginger'), '100g', 12.00, 200, 'VEG-GIN-100G', true),
((SELECT id FROM products WHERE slug='ginger'), '250g', 28.00, 170, 'VEG-GIN-250G', true),

((SELECT id FROM products WHERE slug='garlic'), '250g', 40.00, 190, 'VEG-GAR-250G', true),
((SELECT id FROM products WHERE slug='garlic'), '500g', 75.00, 160, 'VEG-GAR-500G', true),

((SELECT id FROM products WHERE slug='spinach'), '250g bunch', 20.00, 140, 'VEG-SPI-250G', true),
((SELECT id FROM products WHERE slug='spinach'), '500g bunch', 35.00, 120, 'VEG-SPI-500G', true),

((SELECT id FROM products WHERE slug='cauliflower'), '1pc', 45.00, 110, 'VEG-CAU-1PC', true),
((SELECT id FROM products WHERE slug='cauliflower'), '2pc', 85.00, 90, 'VEG-CAU-2PC', true),

((SELECT id FROM products WHERE slug='cabbage'), '1pc', 35.00, 120, 'VEG-CAB-1PC', true),
((SELECT id FROM products WHERE slug='cabbage'), '2pc', 65.00, 90, 'VEG-CAB-2PC', true),

((SELECT id FROM products WHERE slug='capsicum'), '250g', 35.00, 140, 'VEG-CAP-250G', true),
((SELECT id FROM products WHERE slug='capsicum'), '500g', 65.00, 120, 'VEG-CAP-500G', true),

((SELECT id FROM products WHERE slug='brinjal'), '500g', 30.00, 140, 'VEG-BRI-500G', true),
((SELECT id FROM products WHERE slug='brinjal'), '1kg', 55.00, 120, 'VEG-BRI-1KG', true),

((SELECT id FROM products WHERE slug='lady-finger-okra'), '500g', 40.00, 140, 'VEG-OKR-500G', true),
((SELECT id FROM products WHERE slug='lady-finger-okra'), '1kg', 75.00, 120, 'VEG-OKR-1KG', true),

((SELECT id FROM products WHERE slug='beetroot'), '500g', 28.00, 160, 'VEG-BEE-500G', true),
((SELECT id FROM products WHERE slug='beetroot'), '1kg', 52.00, 140, 'VEG-BEE-1KG', true),

((SELECT id FROM products WHERE slug='toned-milk'), '500ml', 27.00, 220, 'DAI-TON-500ML', true),
((SELECT id FROM products WHERE slug='toned-milk'), '1L', 52.00, 240, 'DAI-TON-1L', true),

((SELECT id FROM products WHERE slug='full-cream-milk'), '500ml', 32.00, 200, 'DAI-FCM-500ML', true),
((SELECT id FROM products WHERE slug='full-cream-milk'), '1L', 62.00, 220, 'DAI-FCM-1L', true),

((SELECT id FROM products WHERE slug='curd-dahi'), '200g', 20.00, 180, 'DAI-CUR-200G', true),
((SELECT id FROM products WHERE slug='curd-dahi'), '500g', 45.00, 170, 'DAI-CUR-500G', true),
((SELECT id FROM products WHERE slug='curd-dahi'), '1kg', 85.00, 120, 'DAI-CUR-1KG', true),

((SELECT id FROM products WHERE slug='paneer'), '200g', 85.00, 120, 'DAI-PAN-200G', true),
((SELECT id FROM products WHERE slug='paneer'), '500g', 190.00, 90, 'DAI-PAN-500G', true),

((SELECT id FROM products WHERE slug='butter'), '100g', 54.00, 130, 'DAI-BUT-100G', true),
((SELECT id FROM products WHERE slug='butter'), '500g', 255.00, 90, 'DAI-BUT-500G', true),

((SELECT id FROM products WHERE slug='ghee'), '500ml', 290.00, 80, 'DAI-GHE-500ML', true),
((SELECT id FROM products WHERE slug='ghee'), '1L', 560.00, 70, 'DAI-GHE-1L', true),

((SELECT id FROM products WHERE slug='cheese-slices'), '10 slices', 140.00, 90, 'DAI-CHS-10S', true),
((SELECT id FROM products WHERE slug='cheese-slices'), '20 slices', 265.00, 80, 'DAI-CHS-20S', true),

((SELECT id FROM products WHERE slug='eggs-white'), '6 pcs', 45.00, 220, 'DAI-EGG-6PC', true),
((SELECT id FROM products WHERE slug='eggs-white'), '12 pcs', 85.00, 200, 'DAI-EGG-12PC', true),

((SELECT id FROM products WHERE slug='lassi'), '200ml', 25.00, 160, 'DAI-LAS-200ML', true),
((SELECT id FROM products WHERE slug='lassi'), '1L', 110.00, 90, 'DAI-LAS-1L', true),

((SELECT id FROM products WHERE slug='white-bread'), '400g', 40.00, 180, 'BAK-BRE-400G', true),
((SELECT id FROM products WHERE slug='white-bread'), '700g', 60.00, 120, 'BAK-BRE-700G', true),

((SELECT id FROM products WHERE slug='burger-buns'), 'pack of 4', 35.00, 160, 'BAK-BUN-4PK', true),
((SELECT id FROM products WHERE slug='burger-buns'), 'pack of 6', 48.00, 140, 'BAK-BUN-6PK', true),

((SELECT id FROM products WHERE slug='chicken-curry-cut'), '500g', 160.00, 120, 'MEA-CHK-500G', true),
((SELECT id FROM products WHERE slug='chicken-curry-cut'), '1kg', 310.00, 90, 'MEA-CHK-1KG', true),

((SELECT id FROM products WHERE slug='mutton-curry-cut'), '500g', 380.00, 70, 'MEA-MUT-500G', true),
((SELECT id FROM products WHERE slug='mutton-curry-cut'), '1kg', 740.00, 50, 'MEA-MUT-1KG', true),

((SELECT id FROM products WHERE slug='basmati-rice'), '1kg', 110.00, 220, 'STA-BAS-1KG', true),
((SELECT id FROM products WHERE slug='basmati-rice'), '5kg', 520.00, 120, 'STA-BAS-5KG', true),

((SELECT id FROM products WHERE slug='wheat-atta'), '1kg', 55.00, 240, 'STA-ATT-1KG', true),
((SELECT id FROM products WHERE slug='wheat-atta'), '5kg', 260.00, 140, 'STA-ATT-5KG', true),

((SELECT id FROM products WHERE slug='sunflower-oil'), '1L', 140.00, 180, 'OIL-SUN-1L', true),
((SELECT id FROM products WHERE slug='sunflower-oil'), '5L', 680.00, 80, 'OIL-SUN-5L', true),

((SELECT id FROM products WHERE slug='glucose-biscuits'), 'pack', 10.00, 260, 'SNK-GLU-PK', true),
((SELECT id FROM products WHERE slug='glucose-biscuits'), 'family pack', 30.00, 200, 'SNK-GLU-FPK', true),

((SELECT id FROM products WHERE slug='cola-soft-drink'), '750ml', 40.00, 160, 'BEV-COL-750ML', true),
((SELECT id FROM products WHERE slug='cola-soft-drink'), '2L', 95.00, 120, 'BEV-COL-2L', true),

((SELECT id FROM products WHERE slug='detergent-powder'), '1kg', 120.00, 200, 'HOU-DET-1KG', true),
((SELECT id FROM products WHERE slug='detergent-powder'), '3kg', 340.00, 120, 'HOU-DET-3KG', true);
